### ISSUE TITLE
Возможность отключить магазин (за карму) в группах

### ISSUE THREAD

**Issue by AlexWayfer** [AxeniaDevTeam/Axenia#4]
Здравствуйте.

Функциональность подсчёта полезности участников в группе полезна.

Но вот магазин с шутками и котиками ни к чему. Хотелось бы его отключить.

**Comment by delef** [comment]
Поддерживаю

**Comment by abrikoseg** [comment]
> Здравствуйте.
> 
> Функциональность подсчёта полезности участников в группе полезна.
> 
> Но вот магазин с шутками и котиками ни к чему. Хотелось бы его отключить.

Отключается в настройках с помощью команды  /setting в группе.

**Comment by AlexWayfer** [comment]
> Отключается в настройках с помощью команды /setting в группе.

Прошу прощения, смотрел в личной беседе.
